### ISSUE TITLE
Docker container crashes

### ISSUE THREAD

**Issue by GabMgt** [nosqlclient/nosqlclient#145]
Hello, first let me congratulate you for your awesome job, your project is very promising.

I have few issues with it, so I will create one Github issue for each.

First issue: The docker container crashes after a while. I tried to restart it but after 2 minutes it crashed again. Here is the logs :

```
[[[[[ /opt/mongoclient ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
I20160804-07:18:48.792(0)? info: [connect] mongodb://192.168.0.49:27003/cloud?readPreference=secondary connectTimeoutMS=3000, socketTimeoutMS=5000, sslValidate=false
I20160804-07:19:01.993(0)? info: [ { stats: [ {} ] } ] 'convertIds: true' 'convertDates: true' 'cloud'
I20160804-07:19:48.023(0)? info: [connect] mongodb://192.168.0.49:27003/cloud?readPreference=secondary connectTimeoutMS=3000, socketTimeoutMS=5000, sslValidate=false
I20160804-07:20:01.763(0)? info: [ { command: [ [Object] ] } ] false false false
I20160804-07:20:13.706(0)? info: [getFileInfos] fs
I20160804-07:20:20.619(0)? info: [getFileInfos] fs
I20160804-07:20:22.475(0)? info: [getFileInfos] fs
I20160804-07:20:55.623(0)? info: [uploadFile] fs 90Tech_diagram.png  {}
I20160804-07:20:55.791(0)? info: [getFileInfos] fs
I20160804-07:21:38.631(0)? info: [getFileInfos] fs
I20160804-07:21:39.499(0)? info: [ { command: [ [Object] ] } ] false false false
I20160804-07:21:47.707(0)? info: [ { stats: [ {} ] } ] 'convertIds: true' 'convertDates: true' 'cloud'
I20160804-07:22:03.751(0)? info: [connect] mongodb://192.168.0.49:27003/cloud?readPreference=secondary connectTimeoutMS=3000, socketTimeoutMS=5000, sslValidate=false
I20160804-07:22:25.896(0)? info: [ { command: [ [Object] ] } ] false false false
I20160804-07:22:30.533(0)? info: [getFileInfos] fs
I20160804-07:22:50.361(0)? info: [connect] mongodb://192.168.0.49:27003/cloud?readPreference=secondary connectTimeoutMS=3000, socketTimeoutMS=5000, sslValidate=false
I20160804-07:23:19.600(0)? info: [ { find: [ {} ] }, { limit: [ 1 ] }, { next: [] } ] 'convertIds: true' 'convertDates: true' 'cloud'
I20160804-07:24:22.326(0)? info: [connect] mongodb://192.168.0.49:27003/cloud?readPreference=secondary connectTimeoutMS=3000, socketTimeoutMS=5000, sslValidate=false
I20160804-07:24:52.571(0)? info: [ { find: [ [Object] ] }, { limit: [ 1 ] }, { next: [] } ] 'convertIds: true' 'convertDates: true' 'cloudevents'
I20160804-07:25:02.855(0)? info: [ { find: [ [Object] ] }, { limit: [ 1 ] }, { next: [] } ] 'convertIds: true' 'convertDates: true' 'cloudevents'
I20160804-07:25:17.320(0)? info: [connect] mongodb://192.168.0.49:27003/cloud?readPreference=secondary connectTimeoutMS=3000, socketTimeoutMS=5000, sslValidate=false
I20160804-07:25:18.299(0)? info: [ { command: [ [Object] ] } ] false false false
I20160804-07:25:25.853(0)? info: [ { stats: [ {} ] } ] 'convertIds: true' 'convertDates: true' 'cloudJobs'
I20160804-07:25:29.472(0)? info: [ { stats: [ {} ] } ] 'convertIds: true' 'convertDates: true' 'cloudJobs'
I20160804-07:25:29.489(0)? info: [ { count: [ [Object] ] } ] 'convertIds: true' 'convertDates: true' 'cloudJobs'
I20160804-07:25:29.501(0)? info: [ { find: [ [Object] ] }, { toArray: [] } ] 'convertIds: true' 'convertDates: true' 'cloudJobs'
I20160804-07:25:42.279(0)? info: [ { stats: [ {} ] } ] 'convertIds: true' 'convertDates: true' 'cloudJobs'
I20160804-07:25:42.302(0)? info: [ { count: [ {} ] } ] 'convertIds: true' 'convertDates: true' 'cloudJobs'
I20160804-07:25:59.865(0)? info: [ { stats: [ {} ] } ] 'convertIds: true' 'convertDates: true' 'cloudJobs'
I20160804-07:26:00.335(0)? info: [ { find: [ {} ] },
I20160804-07:26:00.335(0)?   { skip: [ 10 ] },
I20160804-07:26:00.335(0)?   { limit: [ 10 ] },
I20160804-07:26:00.335(0)?   { toArray: [] } ] 'convertIds: true' 'convertDates: true' 'cloudJobs'
I20160804-07:27:28.751(0)? info: [ { stats: [ {} ] } ] 'convertIds: true' 'convertDates: true' 'fs.chunks'
I20160804-07:27:33.433(0)? info: [ { stats: [ {} ] } ] 'convertIds: true' 'convertDates: true' 'fs.chunks'
I20160804-07:27:33.455(0)? info: [ { find: [ {} ] },
I20160804-07:27:33.455(0)?   { skip: [ 10 ] },
I20160804-07:27:33.455(0)?   { limit: [ 10 ] },
I20160804-07:27:33.455(0)?   { toArray: [] } ] 'convertIds: true' 'convertDates: true' 'fs.chunks'
I20160804-07:27:40.059(0)? info: [ { stats: [ {} ] } ] 'convertIds: true' 'convertDates: true' 'fs.files'
I20160804-07:29:23.956(0)? info: [ { stats: [ {} ] } ] 'convertIds: true' 'convertDates: true' 'fs.chunks'
I20160804-07:29:28.968(0)? info: [ { stats: [ {} ] } ] 'convertIds: true' 'convertDates: true' 'fs.chunks'
I20160804-07:29:29.984(0)? info: [ { find: [ {} ] },
I20160804-07:29:29.985(0)?   { skip: [ 10 ] },
I20160804-07:29:29.985(0)?   { limit: [ 10 ] },
I20160804-07:29:29.985(0)?   { toArray: [] } ] 'convertIds: true' 'convertDates: true' 'fs.chunks'
I20160804-07:29:34.604(0)? info: [ { stats: [ {} ] } ] 'convertIds: true' 'convertDates: true' 'cloudJobs'
I20160804-07:29:44.837(0)? info: [ { stats: [ {} ] } ] 'convertIds: true' 'convertDates: true' 'cloudJobs'
I20160804-07:29:44.857(0)? info: [ { count: [ {} ] } ] 'convertIds: true' 'convertDates: true' 'cloudJobs'
I20160804-07:30:00.423(0)? info: [ { find: [ {} ] }, { limit: [ 1 ] }, { next: [] } ] 'convertIds: true' 'convertDates: true' 'cloudJobs'
I20160804-07:30:54.609(0)? info: [ { profilingInfo: [] } ] false false true
I20160804-07:31:01.571(0)? info: [ { replSetGetStatus: [] } ] false false true
I20160804-07:31:06.509(0)? info: [ { serverInfo: [] } ] false false true
I20160804-07:31:39.560(0)? info: [ { listDatabases: [] } ] false false true
I20160804-07:31:43.649(0)? info: [ { serverStatus: [] } ] false false true
I20160804-07:33:38.033(0)? info: [ { buildInfo: [] } ] false false true
I20160804-07:33:43.768(0)? info: [ { command: [ [Object] ] } ] false false false
I20160804-07:35:17.023(0)? info: [connect] mongodb://192.168.0.49:27003/cloud?readPreference=secondary connectTimeoutMS=3000, socketTimeoutMS=5000, sslValidate=false
npm-container: updating npm dependencies -- mongodb, mongodb-backup,
mongodb-restore, tunnel-ssh, cheerio, winston...

/root/.meteor/packages/coffeescript/.1.1.3.w7qi4y++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
Error: EXDEV, cross-device link not permitted '/opt/mongoclient/packages/npm-container/.npm/package'
    at Object.fs.renameSync (fs.js:555:18)
    at Object.wrapper [as rename] (/tools/fs/files.js:1374:35)
    at Object.files.renameDirAlmostAtomically (/tools/fs/files.js:819:11)
    at completeNpmDirectory (/tools/isobuild/meteor-npm.js:485:9)
    at updateExistingNpmDirectory (/tools/isobuild/meteor-npm.js:440:3)
    at Object.meteorNpm.updateDependencies (/tools/isobuild/meteor-npm.js:91:7)
    at Object.compile (/tools/isobuild/compiler.js:119:19)
    at /tools/isobuild/isopack-cache.js:360:30
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._loadLocalPackage (/tools/isobuild/isopack-cache.js:315:18)
    at /tools/isobuild/isopack-cache.js:249:16
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/isopack-cache.js:248:17
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:239:20)
    at /tools/isobuild/isopack-cache.js:76:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.3.4_4.845h3e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object].eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:75:24)
    at /tools/project-context.js:792:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._.extend._buildLocalPackages (/tools/project-context.js:791:18)
    at /tools/project-context.js:284:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:274:18)
    at /tools/project-context.js:266:12
    at Function.run (/tools/tool-env/profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:265:13)
    at /tools/runners/run-app.js:557:29
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundleApp (/tools/runners/run-app.js:556:31)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
[[[[[ /opt/mongoclient ]]]]]

=> Started proxy.
=> Started MongoDB.
npm-container: updating npm dependencies -- mongodb, mongodb-backup,
mongodb-restore, tunnel-ssh, cheerio, winston...

/root/.meteor/packages/templating/.1.1.13.1v1xmti++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
Error: EXDEV, cross-device link not permitted '/opt/mongoclient/packages/npm-container/.npm/package'
    at Object.fs.renameSync (fs.js:555:18)
    at Object.wrapper [as rename] (/tools/fs/files.js:1374:35)
    at Object.files.renameDirAlmostAtomically (/tools/fs/files.js:819:11)
    at completeNpmDirectory (/tools/isobuild/meteor-npm.js:485:9)
    at updateExistingNpmDirectory (/tools/isobuild/meteor-npm.js:440:3)
    at Object.meteorNpm.updateDependencies (/tools/isobuild/meteor-npm.js:91:7)
    at Object.compile (/tools/isobuild/compiler.js:119:19)
    at /tools/isobuild/isopack-cache.js:360:30
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._loadLocalPackage (/tools/isobuild/isopack-cache.js:315:18)
    at /tools/isobuild/isopack-cache.js:249:16
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/isopack-cache.js:248:17
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:239:20)
    at /tools/isobuild/isopack-cache.js:76:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.3.4_4.845h3e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object].eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:75:24)
    at /tools/project-context.js:792:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._.extend._buildLocalPackages (/tools/project-context.js:791:18)
    at /tools/project-context.js:284:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:274:18)
    at /tools/project-context.js:266:12
    at Function.run (/tools/tool-env/profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:265:13)
    at /tools/runners/run-app.js:557:29
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundleApp (/tools/runners/run-app.js:556:31)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
```

Thank you very much!

**Comment by rsercano** [comment]
Hi there,

thanks for your kind opinions :) I see these issues first time, there are 2.3k pulls right now, it's probably about something else.  But to deep dive, I need to know some more details. 

Could you please tell me what's the npm and meteor versions of your docker image ? (I know they have to be latest but that can be an issue)

Cheers

**Comment by GabMgt** [comment]
Thank for you response, Meteor is: 1.3.4.4

But I can't find the npm binary to check the version.

**Comment by rsercano** [comment]
Alright then will check this thanks for the feedback :)

**Comment by GabMgt** [comment]
No problem, don't hesitate if you want more informations.

**Comment by rsercano** [comment]
Couldn't reproduce for now, if you encounter this again please reopen, or someone encounter this, will need to deep dive more. Currently I'm closing this, thanks
