### ISSUE TITLE
Latest docker image crashes

### ISSUE THREAD

**Issue by shipmaster** [nosqlclient/nosqlclient#151]
The docker image was working fine a couple of weeks ago. I just pulled the latest on a fresh docker-machine, got this error when I hit the url in the browser

```
/root/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
                    throw(ex);
                    ^

Error: Can't find npm module 'winston'. Did you forget to call 'Npm.depends' in package.js within    the 'modules-runtime' package?
at Object.Npm.require (/opt/mongoclient/.meteor/local/build/programs/server/boot.js:203:17)
at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:88:1)
at meteorInstall.server.internal.logging.winston.js (server/internal/logging/winston.js:4:10)
at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
at /opt/mongoclient/.meteor/local/build/programs/server/app/app.js:2067:1
at /opt/mongoclient/.meteor/local/build/programs/server/boot.js:297:10
at Array.forEach (native)
at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
Exited with code: 1
Your application is crashing. Waiting for file change.
```

**Comment by rsercano** [comment]
Thanks for the feedback, will take care of this asap.

**Comment by rsercano** [comment]
Could you please retry ? It should work now.
