### ISSUE TITLE
Docker image crashes

### ISSUE THREAD

**Issue by michaelfreund** [nosqlclient/nosqlclient#168]
Launched mongoclient with

```
docker run -d -p 3000:3000 --name mongoclient mongoclient/mongoclient
```

and when I do a `docker logs mongoclient` I see the following error

```
=> Started proxy.
=> Started MongoDB.

/root/.meteor/packages/coffeescript/.1.2.4_1.1v4a1kr++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

TypeError: Method Uint8Array.length called on incompatible receiver [object Object]
    at Buffer.get length (native)
    at /tools/isobuild/compiler-plugin.js:69:22
    at Array.reduce (native)
    at LRUCache.length [as _lengthCalculator] (/tools/isobuild/compiler-plugin.js:68:18)
    at LRUCache.set (/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/lru-cache/lib/lru-cache.js:166:18)
    at PackageSourceBatch._linkJS (/tools/isobuild/compiler-plugin.js:1317:22)
    at PackageSourceBatch.getResources (/tools/isobuild/compiler-plugin.js:1222:28)
    at /tools/isobuild/bundler.js:951:37
    at Array.forEach (native)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:933:19)
    at /tools/isobuild/bundler.js:701:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:692:18)
    at /tools/isobuild/bundler.js:2586:14
    at /tools/isobuild/bundler.js:2675:20
    at Array.forEach (native)
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2674:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2567:31)
    at /tools/isobuild/bundler.js:2514:32
    at Object.withCache (/tools/fs/files.js:1585:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2514:16)
    at /tools/runners/run-app.js:582:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:572:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:625:35)
    at AppRunner._fiber (/tools/runners/run-app.js:884:28)
    at /tools/runners/run-app.js:402:12

```

Running on Ubuntu 14.04.4 LTS with Docker 1.11.1 Build 5604cbe

**Comment by michaelfreund** [comment]
Memory problem. You should have at least 2GB ram when you run mongoclient on a remote instance like a DigitalOcean Droplet.

**Comment by rsercano** [comment]
I hear that first time, there shouldn't be like 2GB restriction will try to check this. Thanks for the feedback.
