### ISSUE TITLE
osx version got only "command+Q" in menu bar after execute .app file

### ISSUE THREAD

**Issue by billiebbb** [nosqlclient/nosqlclient#226]
I am using mac os x 10.12.1 and download osx version of mongoclient. I got nothing in menu bar except "mongoclinet > quit montoclient" after execute .app file. Is there any settings for my os before using mongoclient.app?

**Comment by rsercano** [comment]
Hello, 

there shouldn't be. And mongoclient electron app has nothing special in menu. Are you able to use copy paste shortcuts ?

**Comment by rsercano** [comment]
Are you able to see mongoclient actually ?

**Comment by lum1n** [comment]
version 1.4.0 fails to start on macOS. No window, only shows Mongoclient in menu bar. v1.3 is good.

**Comment by billiebbb** [comment]
Yes, I'm using version 1.4.0(version file v0.35.6) that I download just now. Here is my screenshot after double click on Mongoclient.app.

![image](https://cloud.githubusercontent.com/assets/2628015/20059644/35a8600c-a532-11e6-85d7-2710e2f8245a.png)

**Comment by rsercano** [comment]
I see, could you please try to start from shell and share logs with me ?

**Comment by billiebbb** [comment]
@rsercano 

```
biligedipingguo:Mongoclient-darwin-x64 billiebbb$ Mongoclient.app/Contents/MacOS/Electron 
INFO  electrify:index:  initializing
INFO  electrify:plugins:  use  mongodb
INFO  electrify:plugins:  use  nodejs
INFO  electrify:plugins:  use  socket
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
INFO  electrify:index:  start
INFO  electrify:plugins:  start
INFO  electrify:plugins:mongodb:  starting mongo...
2016-11-07T21:43:56.336+0800 I CONTROL  [initandlisten] MongoDB starting : pid=79642 port=11235 dbpath=/Users/billiebbb/Downloads/Mongoclient-darwin-x64/Mongoclient.app/Contents/Resources/app/db 64-bit host=biligedipingguo
2016-11-07T21:43:56.336+0800 I CONTROL  [initandlisten] db version v3.2.10
2016-11-07T21:43:56.336+0800 I CONTROL  [initandlisten] git version: 79d9b3ab5ce20f51c272b4411202710a082d0317
2016-11-07T21:43:56.336+0800 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 0.9.8zh 14 Jan 2016
2016-11-07T21:43:56.336+0800 I CONTROL  [initandlisten] allocator: system
2016-11-07T21:43:56.336+0800 I CONTROL  [initandlisten] modules: none

2016-11-07T21:43:56.336+0800 I CONTROL  [initandlisten] build environment:
2016-11-07T21:43:56.336+0800 I CONTROL  [initandlisten]     distarch: x86_64
2016-11-07T21:43:56.336+0800 I CONTROL  [initandlisten]     target_arch: x86_64
2016-11-07T21:43:56.337+0800 I CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 11235 }, storage: { dbPath: "/Users/billiebbb/Downloads/Mongoclient-darwin-x64/Mongoclient.app/Contents/Resources/app/db", mmapv1: { smallFiles: true } } }

2016-11-07T21:43:56.338+0800 I -        [initandlisten] Detected data files in /Users/billiebbb/Downloads/Mongoclient-darwin-x64/Mongoclient.app/Contents/Resources/app/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.

2016-11-07T21:43:56.339+0800 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=9G,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),

2016-11-07T21:43:57.663+0800 W STORAGE  [initandlisten] Detected configuration for non-active storage engine mmapv1 when current storage engine is wiredTiger

2016-11-07T21:43:57.864+0800 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker

2016-11-07T21:43:57.876+0800 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/Users/billiebbb/Downloads/Mongoclient-darwin-x64/Mongoclient.app/Contents/Resources/app/db/diagnostic.data'

2016-11-07T21:43:57.939+0800 I NETWORK  [initandlisten] waiting for connections on port 11235

INFO  electrify:plugins:mongodb:  mongo started
INFO  electrify:plugins:socket:  starting socket
2016-11-07T21:43:57.940+0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53035 #1 (1 connection now open)

SockJS v0.3.18 bound to "/electrify"
INFO  electrify:index:  socket listening at 11236
INFO  electrify:plugins:nodejs:  starting meteor...
2016-11-07T21:43:57.949+0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53037 #2 (2 connections now open)

2016-11-07T21:43:57.989+0800 I NETWORK  [conn2] end connection 127.0.0.1:53037 (1 connection now open)
2016-11-07T21:43:57.989+0800 I NETWORK  [conn1] end connection 127.0.0.1:53035 (1 connection now open)

2016-11-07T21:43:59.505+0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53086 #3 (1 connection now open)

/Users/billiebbb/Downloads/Mongoclient-darwin-x64/Mongoclient.app/Contents/Resources/app/app/programs/server/node_modules/fibers/future.js:280
                        throw(ex);
                        ^

Error: Can't find npm module 'tunnel-ssh'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
    at Object.require (/Users/billiebbb/Downloads/Mongoclient-darwin-x64/Mongoclient.app/Contents/Resources/app/app/programs/server/boot.js:200:17)
    at options.fallback (packages/modules-runtime.js:445:18)
    at new require (packages/modules-runtime.js:112:16)
    at meteorInstall.server.imports.mongodb.methods_common.js (server/imports/mongodb/methods_common.js:12:19)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at Module.require (packages/modules-runtime.js:106:16)
    at Module.Mp.import (/Users/billiebbb/Downloads/Mongoclient-darwin-x64/Mongoclient.app/Contents/Resources/app/app/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime.js:70:16)
    at meteorInstall.server.imports.webapp.js (server/imports/webapp.js:1:1)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at Module.require (packages/modules-runtime.js:106:16)
2016-11-07T21:43:59.783+0800 I NETWORK  [conn3] end connection 127.0.0.1:53086 (0 connections now open)
```

update full log

**Comment by rsercano** [comment]
Thank you so much, I guess linux version has same issue too, I'm checking this right now, please download 1.3.0 in the meantime. Sorry for the inconvenience.

**Comment by rsercano** [comment]
I've found the issue, gotta upload new portable for osx in one hour and let you know.

**Comment by rsercano** [comment]
Would you please try again ?

**Comment by billiebbb** [comment]
@rsercano It is work fine now.

**Comment by rsercano** [comment]
@billiebbb glad to hear that :)
