### ISSUE TITLE
Cant find/findOne on a specific collection

### ISSUE THREAD

**Issue by Sivli-Embir** [nosqlclient/nosqlclient#243]
As per our conversation via Boomtrain (in app chat):

Issue: one collection fails when I query it regardless of the selector.
collection name: responses
```
info: [connect] mongodb://[omitted]
info: [ { serverStatus: [] } ] false false true
info: [stats]
info: [ { serverStatus: [] } ] false false true
info: [ { stats: [ {} ] } ] 'convertIds: true' 'convertDates: true' 'responses'
info: [ { find: [ {} ] }, { limit: [ 1 ] }, { next: [] } ] 'convertIds: false' 'convertDates: false' 'responses'
Exception while invoking method 'findOne' TypeError: Cannot call method 'toString' of null
    at convertObjectIDsToString (server/mongodb/helper.js:163:1)
    at convertObjectIDsToString (server/mongodb/helper.js:158:1)
    at convertBSONtoJSON (server/mongodb/helper.js:90:1)
    at proceedQueryExecution (server/mongodb/methods_collection.js:310:1)
    at [object Object].Meteor.methods.findOne (server/mongodb/methods_collection.js:167:1)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
```

**Comment by Sivli-Embir** [comment]
Here is a truncated "anonymized" copy of one of the records 
```
{
	"_id" : "[id]",
	"groupId" : "[id]",
	"userId" : "[id]",
	"date" : {
		"week" : 46,
		"year" : 2016
	},
	"units" : {
		"block" : "B01",
		"nave" : "N01",
		"cama" : "C01"
	},
	"crop" : {
		"name" : "rosa",
		"variety" : "mondial"
	},
	"data" : [
		{
			"segment" : 1,
			"values" : [
				{
					"indicator" : "acaros",
					"value" : 2,
					"indicatorRange" : 3,
					"indicatorAbb" : "ac"
				},
				...
			]
		},
		{
			"segment" : 2,
			"values" : [
				{
					"indicator" : "acaros",
					"value" : 2,
					"indicatorRange" : 3,
					"indicatorAbb" : "ac"
				},
				...
			]
		},
		...
	],
	"coords" : [
		null,
		null
	]
}
```

**Comment by Sivli-Embir** [comment]
Updated to 1.4.0 and everything started working. My bad!

**Comment by rsercano** [comment]
I'm glad your issue is fixed @Kestanous :)
