### ISSUE TITLE
Web: analyze schema fails with "Error: spawn EACCES"

### ISSUE THREAD

**Issue by puncha** [nosqlclient/nosqlclient#274]
I'm using the latest codes in master branch and when i access the schema analyze functionality in web browser, it reports:
```
I20170111-01:12:32.913(-8)? info: [analyzeSchema] [ 'mongodb://10.35.237.136:27017/acadci_admin?readPreference=secondary',
I20170111-01:12:32.914(-8)?   '--quiet',
I20170111-01:12:32.915(-8)?   '--eval',
I20170111-01:12:32.915(-8)?   'var collection ="branches", outputFormat="json"',
I20170111-01:12:32.916(-8)?   '/home/administrator/mongoclient-1.5.0/.meteor/local/build/programs/web.browser/app/mongo/variety/variety.js_' ] mongodb://10.35.237.136:27017/acadci_admin?readPreference=secondary branches
W20170111-01:12:32.921(-8)? (STDERR) error: [analyzeSchema] Error: spawn EACCES
W20170111-01:12:32.921(-8)? (STDERR)     at exports._errnoException (util.js:911:11)
W20170111-01:12:32.922(-8)? (STDERR)     at ChildProcess.spawn (internal/child_process.js:309:11)
W20170111-01:12:32.922(-8)? (STDERR)     at Object.exports.spawn (child_process.js:362:9)
W20170111-01:12:32.923(-8)? (STDERR)     at spawn (/home/administrator/mongoclient-1.5.0/node_modules/cross-spawn/index.js:17:18)
W20170111-01:12:32.924(-8)? (STDERR)     at server/imports/mongodb/methods_common.js:372:27
W20170111-01:12:32.924(-8)? (STDERR)     at [object Object].analyzeSchema (server/imports/mongodb/methods_common.js:371:13)
W20170111-01:12:32.924(-8)? (STDERR)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1712:12)
W20170111-01:12:32.925(-8)? (STDERR)     at packages/ddp-server/livedata_server.js:711:19
W20170111-01:12:32.925(-8)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
W20170111-01:12:32.927(-8)? (STDERR)     at packages/ddp-server/livedata_server.js:709:40
```

**Comment by rsercano** [comment]
Hello there,

can you please use below command to change permissions of application folder:

`chmod  -R 777 /home/administrator/mongoclient-1.5.0/.meteor/local/build/programs/web.browser/app/`

**Comment by puncha** [comment]
@rsercano thanks, it works! It seems the mongo bin: `/home/administrator/mongoclient-1.5.0/.meteor/local/build/programs/web.browser/app/mongo/linux/mongo` requires execution privilege

**Comment by puncha** [comment]
@rsercano will you fix this issue in next release? Shall I keep this issue open or you will create another one to track?

**Comment by rsercano** [comment]
@puncha I'm glad your issue's fixed, let's keep this open, gotta resolve this on next release, thanks for the feedback
