### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by chaitanyya** [nosqlclient/nosqlclient#38]
I'm trying to install it on AWS EC2 instance but I'm getting the following error. Is there any configuration file where I can specify database etc.

**Error:**

```
/root/.meteor/packages/meteor-tool/.1.1.10.m84685++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
TypeError: Object [object Object] has no method 'describe'
    at server/mongodb/packages/npm-container/package.js:4:1
    at /var/www/mongoclient/.meteor/local/build/programs/server/app/server/mongodb/packages/npm-container/package.js:31:4
    at /var/www/mongoclient/.meteor/local/build/programs/server/boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.1.10.m84685++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /var/www/mongoclient/.meteor/local/build/programs/server/boot.js:137:5
Exited with code: 8
Your application is crashing. Waiting for file change.
```

**Comment by rsercano** [comment]
Hello,
as far as I understand you are trying to compile as a meteor application. You can simply specify meteor's mongodb properties by exporting a system variable named as `MONGO_URL` before starting the application by `meteor` command

for instance:

`export MONGO_URL=mongodb://localhost:27017/your_db`

**Comment by lakshmanavaradhan** [comment]
how to install from zip
