### ISSUE TITLE
Failed to connect using docker

### ISSUE THREAD

**Issue by pmatos** [nosqlclient/nosqlclient#381]
`nosqlclient` does not connect using `docker`.

I have a script `run_nosqlclient.sh` that looks like
```
#! /bin/bash
mkdir -p $HOME/tmp/mongodb
docker run --net="host" -p 3000:3000 -v $HOME/tmp/mongodb:/data/db mongoclient/mongoclient:2.1.0
```

I have just upgraded to Fedora 26 and when I run this on an empty `$HOME/tmp/mongodb`:
```
[-] External MONGO_URL not found. Starting local MongoDB...

=> Starting app on port 3000...
2017-07-18T11:20:42.533+0000 I CONTROL  [initandlisten] MongoDB starting : pid=7 port=27017 dbpath=/data/db 64-bit host=andromeda.desktop
2017-07-18T11:20:42.533+0000 I CONTROL  [initandlisten] db version v3.4.2
2017-07-18T11:20:42.533+0000 I CONTROL  [initandlisten] git version: 3f76e40c105fc223b3e5aac3e20dcd026b83b38b
2017-07-18T11:20:42.533+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
2017-07-18T11:20:42.533+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2017-07-18T11:20:42.533+0000 I CONTROL  [initandlisten] modules: none
2017-07-18T11:20:42.533+0000 I CONTROL  [initandlisten] build environment:
2017-07-18T11:20:42.533+0000 I CONTROL  [initandlisten]     distmod: debian81
2017-07-18T11:20:42.533+0000 I CONTROL  [initandlisten]     distarch: x86_64
2017-07-18T11:20:42.533+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2017-07-18T11:20:42.533+0000 I CONTROL  [initandlisten] options: { storage: { engine: "wiredTiger" } }
2017-07-18T11:20:42.537+0000 I STORAGE  [initandlisten] 
2017-07-18T11:20:42.537+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2017-07-18T11:20:42.537+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2017-07-18T11:20:42.537+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=31649M,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),

/opt/meteor/dist/bundle/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^
MongoError: failed to connect to server [127.0.0.1:27017] on first connect
    at Object.Future.wait (/opt/meteor/dist/bundle/programs/server/node_modules/fibers/future.js:449:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:211:27)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Mongo.Collection (packages/mongo/collection.js:99:40)
    at meteorInstall.lib.imports.collections.settings.js (lib/imports/collections/settings.js:6:25)
    at fileEvaluate (packages/modules-runtime.js:197:9)
    at Module.require (packages/modules-runtime.js:120:16)
    at Module.Mp.importSync (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime.js:82:24)
    - - - - -
    at [object Object].<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at emitOne (events.js:77:13)
    at [object Object].emit (events.js:169:7)
    at [object Object].<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at [object Object].g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at [object Object].emit (events.js:172:7)
    at Socket.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
```

**Comment by rsercano** [comment]
Hello @pmatos 

I suspect that it's about your `--net="host"` argument. Nosqlclient connects to an internal mongodb, which is required for itself. And when you set network to host it tries to find a mongodb running on your local machine.

Apart from that you can set **MONGO_URL** environment varaible which is more reliable and setup an another mongodb for nosqlclient. It keeps connections and settings in the mongodb. 

Let me know if that works for you.

**Comment by pmatos** [comment]
@rsercano thanks for the reply. I would like to reuse the mongod I have on my system. So, if I change to:

```
 $ docker run --net="host" -e MONGO_URL="mongodb://localhost:27017" -p 3000:3000 mongoclient/mongoclient:2.1.0
=> Starting app on port 3000...
```

seems to work.

**Comment by rsercano** [comment]
@pmatos great to hear that, closing the issue.

**Comment by helloworldless** [comment]
I can't get the client running in a container using a Mongo instance running on the my local machine. I'm using Mongo 4.0.3, and I tried the commands mentioned above, but I just get the error below. Any ideas?

`{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"}...`

**Comment by rsercano** [comment]
When you're using docker, please check your network with docker is it bridge ? @paltamadura

**Comment by helloworldless** [comment]
I was able to get it working following the steps below.

From what I understand, the `--net="host"` option won't do the trick when running Docker on Mac because `host` refers to the virtual host which runs Docker (see explanation [here](https://forums.docker.com/t/should-docker-run-net-host-work/14215/8?u=paltamadura)). However, opening a port using the `-p` option will work since it actually opens a connection between the container and Mac host machine (and not just to the virtual host running Docker).

1. Run `mongod` on your local machine making sure to bind your host machine's IP address. If you don't bind your host machine's IP address, you will see a warning when starting the Mongo deamon like, "WARNING: This server is bound to localhost. Remote systems will be unable to connect to this server.".  Also, From the [Mongo FAQ](https://docs.atlas.mongodb.com/faq/#can-i-disable-ssl-tls-on-my-deployment), it looks like you cannot run a Mongo server with SSL/TLS disabled, so you'll need to set up SSL/TLS as well. See instructions [here](https://docs.mongodb.com/manual/tutorial/configure-ssl/).
   1. `mongod --bind_ip <host_machine_ip> --sslMode requireSSL --sslAllowConnectionsWithoutCertificates --sslPEMKeyFile <path_to_pem_file>`
1. Start Nosqlclient. Make sure you expose port 27017 between the container and the host machine, and append `/?ssl=true` to the Mongo URL
   1. `docker run -p 27017:27017 -e MONGO_URL="mongodb://<host_machine_ip>:27017/?ssl=true" -p 3000:3000 mongoclient/mongoclient`
