### ISSUE TITLE
docker image can not start

### ISSUE THREAD

**Issue by hzn942** [nosqlclient/nosqlclient#412]
## Expected Behavior

run docker container w/o problem
## Current Behavior

container exit right after started, here is the log from container:
[-] External MONGO_URL not found. Starting local MongoDB...

=> Starting app on port 3000...
2017-11-29T05:06:12.551+0000 I CONTROL  [initandlisten] MongoDB starting : pid=7 port=27017 dbpath=/data/db 64-bit host=fd0daad8fa34
2017-11-29T05:06:12.551+0000 I CONTROL  [initandlisten] db version v3.4.2
2017-11-29T05:06:12.551+0000 I CONTROL  [initandlisten] git version: 3f76e40c105fc223b3e5aac3e20dcd026b83b38b
2017-11-29T05:06:12.551+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
2017-11-29T05:06:12.551+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2017-11-29T05:06:12.551+0000 I CONTROL  [initandlisten] modules: none
2017-11-29T05:06:12.551+0000 I CONTROL  [initandlisten] build environment:
2017-11-29T05:06:12.551+0000 I CONTROL  [initandlisten]     distmod: debian81
2017-11-29T05:06:12.551+0000 I CONTROL  [initandlisten]     distarch: x86_64
2017-11-29T05:06:12.551+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2017-11-29T05:06:12.551+0000 I CONTROL  [initandlisten] options: { storage: { engine: "wiredTiger" } }
2017-11-29T05:06:12.556+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=487M,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-11-29T05:06:12.593+0000 I CONTROL  [initandlisten]
2017-11-29T05:06:12.593+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-11-29T05:06:12.593+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-11-29T05:06:12.593+0000 I CONTROL  [initandlisten]
2017-11-29T05:06:12.602+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
/opt/meteor/dist/bundle/programs/server/boot.js:50
    const { pause } = require("./debug.js");
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/meteor/dist/bundle/main.js:4:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
## Steps to Reproduce (for bugs)

1.docker pull mongoclient/mongoclient
2.docker run -d -p 3000:3000 mongoclient/mongoclient

## Your Environment

* Environment name (docker):
* Operating System and version (osx 10.12):

**Comment by rsercano** [comment]
Hello @hzn942 

thanks for sharing, gotta check asap

**Comment by rsercano** [comment]
@hzn942 could you please pull again, it should work now.

**Comment by hzn942** [comment]
It worked! thank you so much! nice work
