### ISSUE TITLE
Unable to start the nosqlclient docker container once it is killed.

### ISSUE THREAD

**Issue by ghost** [nosqlclient/nosqlclient#417]
On executing `docker run -p 3000:3000 mongoclient/mongoclient`, the container fails to start.

## Current Behavior
The container fails to start, and the logs reveal this stack trace:
`[-] External MONGO_URL not found. Starting local MongoDB...

=> Starting app on port 3000...
2017-12-12T04:59:13.879+0000 I CONTROL  [initandlisten] MongoDB starting : pid=6 port=27017 dbpath=/data/db 64-bit host=7b75f3caff24
2017-12-12T04:59:13.880+0000 I CONTROL  [initandlisten] db version v3.4.2
2017-12-12T04:59:13.880+0000 I CONTROL  [initandlisten] git version: 3f76e40c105fc223b3e5aac3e20dcd026b83b38b
2017-12-12T04:59:13.880+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
2017-12-12T04:59:13.880+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2017-12-12T04:59:13.880+0000 I CONTROL  [initandlisten] modules: none
2017-12-12T04:59:13.880+0000 I CONTROL  [initandlisten] build environment:
2017-12-12T04:59:13.880+0000 I CONTROL  [initandlisten]     distmod: debian81
2017-12-12T04:59:13.880+0000 I CONTROL  [initandlisten]     distarch: x86_64
2017-12-12T04:59:13.880+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2017-12-12T04:59:13.880+0000 I CONTROL  [initandlisten] options: { storage: { engine: "wiredTiger" } }
2017-12-12T04:59:13.880+0000 I STORAGE  [initandlisten] exception in initAndListen: 20 Attempted to create a lock file on a read-only directory: /data/db, terminating
2017-12-12T04:59:13.880+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
2017-12-12T04:59:13.880+0000 I NETWORK  [initandlisten] shutdown: going to flush diaglog...
2017-12-12T04:59:13.880+0000 I CONTROL  [initandlisten] now exiting
2017-12-12T04:59:13.880+0000 I CONTROL  [initandlisten] shutting down with code:100

/opt/meteor/dist/bundle/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Object.Future.wait (/opt/meteor/dist/bundle/programs/server/node_modules/fibers/future.js:449:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:211:27)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Mongo.Collection (packages/mongo/collection.js:99:40)
    at meteorInstall.lib.imports.collections.js (lib/imports/collections.js:3:24)
    at fileEvaluate (packages/modules-runtime.js:333:9)
    at require (packages/modules-runtime.js:228:16)
    at meteorInstall.server.imports.internal.startup.js (server/imports/internal/startup.js:1:226)
    - - - - -
    at [object Object].<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:329:35)
    at emitOne (events.js:77:13)
    at [object Object].emit (events.js:169:7)
    at [object Object].<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at [object Object].g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at [object Object].emit (events.js:172:7)
    at Socket.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
`

## Expected behavior
The docker should start without any errors

## Steps to Reproduce (for bugs)
1. Pull the docker image: `docker pull mongoclient/mongoclient` 
2. Start the container (first time): `docker run -d -p 3000:3000 mongoclient/mongoclient` 
3. Kill the container: `docker kill <container id>`
4. Start the container again: `docker run -d -p 3000:3000 mongoclient/mongoclient` 

##Context
I had to run another process which required access to port 3000. I, therefore decided to kill the docker container, in hopes of assigning another port later. 

## Your Environment

* Nosqlclient version used: 2.2.0
* Operating System and version: Ubuntu 16.04 LTS, kernel version `4.8.0-58-lowlatency`

**Comment by ghost** [comment]
An update: Once killed, I need to restart my computer again to start this container.

**Comment by rsercano** [comment]
Hello @ghosthawkone would you please try to use `latest` tag and let me know how it goes with it ?

**Comment by ghost** [comment]
Sorry for replying late. I'll definitely check that out.
