### ISSUE TITLE
Stuck at loading splash screen

### ISSUE THREAD

**Issue by ajmas** [nosqlclient/nosqlclient#420]
## Expected Behavior

Expect splash screen to disappear and for application to finish start

## Current Behavior

Application launches, shows splash screen and then doesn't do anything visible after that.

Note that if I do a quit then I get the following error:

```
Uncaught Exception:
TypeError: Cannot read property 'kill' of undefined
    at App.<anonymous> (/Applications/Database Admin/Nosqlclient.app/Contents/Resources/app/index.js:343:16)
    at emitOne (events.js:101:20)
    at App.emit (events.js:191:7)
```

Launching the application from the command line, I get the following log output:

```
[MONGOCLIENT] trying to start Mongoclient electron application
[MONGOCLIENT] trying to show loading page while everything is getting ready, loading page url: file:/Applications/Database Admin/Nosqlclient.app/Contents/Resources/app/loading.html
2018-01-08 23:36:42.446 Nosqlclient[15226:6997240] *** WARNING: Textured window <AtomNSWindow: 0x7fab91559ac0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
[MONGOCLIENT] trying to start mongod process
[MONGOCLIENT] detected mongod executable path: /Applications/Database Admin/Nosqlclient.app/Contents/Resources/app/bin/mongod
[MONGOCLIENT] detected mongod data directory: /Users/ajmas/Library/Preferences/Mongoclient/db
[MONGOCLIENT] trying to create data dir and removing mongod.lock just in case
[MONGOCLIENT] trying to find free port for spawn
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.3.7/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 3 
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.3.7/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 4 
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.3.7/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 5 
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.3.7/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 6 
[MONGOCLIENT] trying to find free port for spawn
[MONGOCLIENT] trying to find free port for spawn
[MONGOCLIENT] trying to spawn mongod process with port: 11237
[MONGOCLIENT] [MONGOD-STDOUT] 2018-01-08T23:36:42.876-0500 I CONTROL  [initandlisten] MongoDB starting : pid=15229 port=11237 dbpath=/Users/ajmas/Library/Preferences/Mongoclient/db 64-bit host=ghostwalker-delta.local
2018-01-08T23:36:42.877-0500 I CONTROL  [initandlisten] db version v3.2.11-39-g1c43b90
2018-01-08T23:36:42.877-0500 I CONTROL  [initandlisten] git version: 1c43b90c0483bc7574fecd0eaeee610480cc9217
2018-01-08T23:36:42.877-0500 I CONTROL  [initandlisten] allocator: system

[MONGOCLIENT] [MONGOD-STDOUT] 2018-01-08T23:36:42.878-0500 I CONTROL  [initandlisten] modules: none
2018-01-08T23:36:42.878-0500 I CONTROL  [initandlisten] build environment:
2018-01-08T23:36:42.878-0500 I CONTROL  [initandlisten]     distarch: x86_64
2018-01-08T23:36:42.878-0500 I CONTROL  [initandlisten]     target_arch: x86_64
2018-01-08T23:36:42.878-0500 I CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 11237 }, storage: { dbPath: "/Users/ajmas/Library/Preferences/Mongoclient/db", mmapv1: { smallFiles: true } } }
2018-01-08T23:36:42.879-0500 I -        [initandlisten] Detected data files in /Users/ajmas/Library/Preferences/Mongoclient/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2018-01-08T23:36:42.879-0500 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=4G,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),

[MONGOCLIENT] [MONGOD-STDOUT] 2018-01-08T23:36:42.880-0500 E STORAGE  [initandlisten] WiredTiger (35) [1515472602:880213][15229:0x7fffae8c4340], wiredtiger_open: /Users/ajmas/Library/Preferences/Mongoclient/db/WiredTiger.lock: handle-lock: fcntl: Resource temporarily unavailable
2018-01-08T23:36:42.880-0500 E STORAGE  [initandlisten] WiredTiger (16) [1515472602:880262][15229:0x7fffae8c4340], wiredtiger_open: WiredTiger database is already being managed by another process: Resource busy
2018-01-08T23:36:42.880-0500 I -        [initandlisten] Assertion: 28595:16: Resource busy
2018-01-08T23:36:42.880-0500 I STORAGE  [initandlisten] exception in initAndListen: 28595 16: Resource busy, terminating

[MONGOCLIENT] [MONGOD-STDOUT] 2018-01-08T23:36:42.880-0500 I CONTROL  [initandlisten] dbexit:  rc: 100

[MONGOCLIENT] [MONGOD-EXIT] 100
```

Nothing visible in system log.

## Possible Solution

Having been able to see the log, a `ps auxww` revealed the following process running:

```
/Applications/Database Admin/Nosqlclient.app/Contents/Resources/app/bin/mongod --dbpath /Users/ajmas/Library/Preferences/Mongoclient/db --port 11235 --bind_ip 127.0.0.1 --smallfiles
```
Killing this process allowed the application to launch.

## Steps to Reproduce (for bugs)

1. Go to Finder
2. Double click on Nosqlclient.app
3. See splash screen and that's it.

## Context

Trying to launch the application.

## Your Environment

* Nosqlclient version used: 2.2.0
* Environment name (e.g. chrome 39, portable, docker): portable
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): 10.13.2

**Comment by rsercano** [comment]
Hello @ajmas we'll fix it asap, but at its best it can take a few months, you can read about it from [here](medium.com/mongoclient/were-having-a-break-for-a-short-time-a845ac70ebd6) sorry for the inconvenince

**Comment by rsercano** [comment]
I guess, the issue is nosqlclient is not waiting for mongodb to start before it starts, will check this during next release

**Comment by ajmas** [comment]
I believe I resolved this by killing any mongo process I found, along with anything related to the app. I then started everything. It’s been a while.

**Comment by rsercano** [comment]
Oh thank you for your feedback @ajmas
