### ISSUE TITLE
Data directory /data/db not found., terminating

### ISSUE THREAD

**Issue by luckydonald** [nosqlclient/nosqlclient#511]
```bash
I STORAGE  [initandlisten] exception in initAndListen: 29 Data directory /data/db not found., terminating
```
and 
```
MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
```
## Expected Behavior

Launching the container works

## Current Behavior

It doesn't, lol.

## Steps to Reproduce (for bugs)

```yml
mongo_browser:
    image: mongoclient/mongoclient:2.2.0
    restart: "no"
    environment:
      ROOT_URL: "https://${URL_HOSTNAME}/"
      MONGO_HOST: mongo_browser
      MONGOCLIENT_AUTH: "true"
      MONGOCLIENT_USERNAME: ${MONGO_BROWSER_USERNAME}
      MONGOCLIENT_PASSWORD: ${MONGO_BROWSER_PASSWORD}
    networks:
      - mongo
    volumes:
      - /data/mongo_browser/:/data
 ```
```bash
docker-compose up -d mongo_browser
```

## Context
```
$ docker-compose logs -f --tail 100 mongo_browser
WARNING: The POSTGRES_ADMIN_PASS variable is not set. Defaulting to a blank string.
Attaching to dockertgbot_mongo_browser_1
mongo_browser_1            | [-] External MONGO_URL not found. Starting local MongoDB...
mongo_browser_1            | => Starting app on port 3000...
mongo_browser_1            | 2019-06-14T10:23:46.442+0000 I CONTROL  [initandlisten] MongoDB starting : pid=8 port=27017 dbpath=/data/db 64-bit host=bf4ebff25308
mongo_browser_1            | 2019-06-14T10:23:46.442+0000 I CONTROL  [initandlisten] db version v3.4.2
mongo_browser_1            | 2019-06-14T10:23:46.442+0000 I CONTROL  [initandlisten] git version: 3f76e40c105fc223b3e5aac3e20dcd026b83b38b
mongo_browser_1            | 2019-06-14T10:23:46.442+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
mongo_browser_1            | 2019-06-14T10:23:46.442+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo_browser_1            | 2019-06-14T10:23:46.442+0000 I CONTROL  [initandlisten] modules: none
mongo_browser_1            | 2019-06-14T10:23:46.442+0000 I CONTROL  [initandlisten] build environment:
mongo_browser_1            | 2019-06-14T10:23:46.442+0000 I CONTROL  [initandlisten]     distmod: debian81
mongo_browser_1            | 2019-06-14T10:23:46.442+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongo_browser_1            | 2019-06-14T10:23:46.442+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongo_browser_1            | 2019-06-14T10:23:46.442+0000 I CONTROL  [initandlisten] options: { storage: { engine: "wiredTiger" } }
mongo_browser_1            | 2019-06-14T10:23:46.442+0000 I STORAGE  [initandlisten] exception in initAndListen: 29 Data directory /data/db not found., terminating
mongo_browser_1            | 2019-06-14T10:23:46.442+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
mongo_browser_1            | 2019-06-14T10:23:46.442+0000 I NETWORK  [initandlisten] shutdown: going to flush diaglog...
mongo_browser_1            | 2019-06-14T10:23:46.442+0000 I CONTROL  [initandlisten] now exiting
mongo_browser_1            | 2019-06-14T10:23:46.442+0000 I CONTROL  [initandlisten] shutting down with code:100
mongo_browser_1            | /opt/meteor/dist/bundle/programs/server/node_modules/fibers/future.js:313
mongo_browser_1            |                                            throw(ex);
mongo_browser_1            |                                            ^
mongo_browser_1            | MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
mongo_browser_1            |     at Object.Future.wait (/opt/meteor/dist/bundle/programs/server/node_modules/fibers/future.js:449:15)
mongo_browser_1            |     at new MongoConnection (packages/mongo/mongo_driver.js:211:27)
mongo_browser_1            |     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
mongo_browser_1            |     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
mongo_browser_1            |     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
mongo_browser_1            |     at new Mongo.Collection (packages/mongo/collection.js:99:40)
mongo_browser_1            |     at meteorInstall.lib.imports.collections.js (lib/imports/collections.js:3:24)
mongo_browser_1            |     at fileEvaluate (packages/modules-runtime.js:333:9)
mongo_browser_1            |     at require (packages/modules-runtime.js:228:16)
mongo_browser_1            |     at meteorInstall.server.imports.internal.startup.js (server/imports/internal/startup.js:1:226)
mongo_browser_1            |     - - - - -
mongo_browser_1            |     at [object Object].<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:329:35)
mongo_browser_1            |     at emitOne (events.js:77:13)
mongo_browser_1            |     at [object Object].emit (events.js:169:7)
mongo_browser_1            |     at [object Object].<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
mongo_browser_1            |     at [object Object].g (events.js:260:16)
mongo_browser_1            |     at emitTwo (events.js:87:13)
mongo_browser_1            |     at [object Object].emit (events.js:172:7)
mongo_browser_1            |     at Socket.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
mongo_browser_1            |     at Socket.g (events.js:260:16)
mongo_browser_1            |     at emitOne (events.js:77:13)
```

## Your Environment

```bash
$ docker version
Client: Docker Engine - Community
 Version:           18.09.3
 API version:       1.38 (downgraded from 1.39)
 Go version:        go1.12
 Git commit:        774a1f4
 Built:             Fri Mar  1 04:14:27 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:26:20 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by rsercano** [comment]
Hello @luckydonald 

could you please try after removing this line; `MONGO_HOST: mongo_browser` from your compose file.

**Comment by luckydonald** [comment]
If I change the volumes to include the `db` folder,
```yml
volumes:
      - /data/mongo_browser/:/data/db
```
I get 
```
 I STORAGE  [initandlisten] exception in initAndListen: 20 Attempted to create a lock file on a read-only directory: /data/db, terminating
```

**Comment by luckydonald** [comment]
Hey @rsercano, removing `MONGO_HOST: mongo_browser` doesn't change anything.

**Comment by luckydonald** [comment]
Using `:latest` didn't yield different results, other than the stack trace being formatted different.

**Comment by luckydonald** [comment]
It seems that `/data/db` cannot be created correctly.

**Comment by rsercano** [comment]
Ahh, you're right you needed to provide `db` folder too in the path, please try to remove your local `/data/mongo_browser/` folder and try again with the `db` in the path.

**Comment by luckydonald** [comment]
I removed the host folder, so it get's recreated the next time.
```
exception in initAndListen: 20 Attempted to create a lock file on a read-only directory: /data/db, terminating
```

**Comment by luckydonald** [comment]
Adding `command: sleep 600` to the service declaration and going into the container with
```bash
$ docker-compose exec mongo_browser /bin/bash
node@eb6d8b74ed63:/opt/meteor/dist/bundle$

node@eb6d8b74ed63:/opt/meteor/dist/bundle$ ls -lah /data   
total 12K
drwxr-xr-x  3 node node 4.0K Aug 23  2017 .
drwxr-xr-x 47 root root 4.0K Jun 14 10:46 ..
drwxr-xr-x  2 root root 4.0K Jun 14 10:44 db

node@eb6d8b74ed63:/opt/meteor/dist/bundle$ ls -laaaaaah /data/db 
total 8.0K
drwxr-xr-x 2 root root 4.0K Jun 14 10:44 .
drwxr-xr-x 3 node node 4.0K Aug 23  2017 ..
```

So basically there is missing a `chown node:node  /data/db` in the entrypoint script.
**Edit**:
Or  in the `Dockerfile`. If the folder is already created in the Dockerfile, it will be copied to the host on first launch, and would keep the correct `node:node` user:group flags.

**Comment by luckydonald** [comment]
What id has that `node` user? So I can try chowning it on the host.

**Comment by rsercano** [comment]
that's actually being done in the scripts check here; https://github.com/nosqlclient/nosqlclient/blob/59da521ac30a8c94b262f7e672620f6a7e573fa4/.docker/install-mongo.sh#L20

**Comment by luckydonald** [comment]
Strange. I assume you couldn't reproduce it?

**Comment by rsercano** [comment]
Yes, unfortunately I couldn't reproduce it but you can try to use your own mongodb image for nosqlclient by setting `MONGO_URL` env. variable ?

**Comment by luckydonald** [comment]
In fact, I tried that before, but couldn't make it to work either.

Couldn't find any documentation on how to prepare the Mongodb for use with onsqlqlient.
I.e. what permission, indexes, etc. to create.
I don't wanna give full admin permissions.

**Comment by rsercano** [comment]
Actually there're docs here; https://www.nosqlclient.com/docs/start.html and it just requires a simple `mongod` instance to be running. Since `MONGO_URL` itself includes username, password, authdb etc. You can use anything you want. You can just create a simple database for nosqlclent and create one user for it. And set these credentials in MONGO_URL env. variable

**Comment by luckydonald** [comment]
I got it running with creating a database and user from an existing Mongodb instance.

**Comment by rsercano** [comment]
Great @luckydonald, I assume this can be closed now.

**Comment by luckydonald** [comment]
Still the issue (the build-in db not working) wasn't resolved.

**Comment by rsercano** [comment]
Oh, sorry to hear that I'll try to reproduce it @luckydonald

**Comment by jashar-raven** [comment]
This is easy to reproduce for me.  

How to reproduce:

```
docker run -d -p 3000:3000 --name nosqlclienttest01 -v /Users/jasrh/Apps/nosqlclienttest01:/data/db mongoclient/mongoclient

docker stop nosqlclienttest01

docker start nosqlclienttest01 # starts and immediately dies
```

**Comment by jashar-raven** [comment]
I have fixed this.   In a local MongoDB container, the db always shuts down uncleanly.  When a restart happens, the app tries to start before the db has had time to recover, resulting in the MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017 error.  

The entrypoint startup script already utilized a delay env variable, STARTUP_DELAY, making this an easy fix:

When using run:

`docker run -d -p 3000:3000 --name nosqlclienttest02 -e STARTUP_DELAY=30 -v /Users/jasrh/Apps/nosqlclienttest01:/data/db mongoclient/mongoclient `

or a STARTUP_DELAY:30 in a docker compose.   I think 30 seconds is a little bit high, but it works for testing purposes.  Each system will have a different recovery time depending on the host system and the size of the meteor db.   Hopefully this helps others.

**Comment by rsercano** [comment]
I'm glad this's fixed without any additional effort.  Thank you @jasrh
