### ISSUE TITLE
Latest mongoclient docker image crashes

### ISSUE THREAD

**Issue by junaid-ali** [nosqlclient/nosqlclient#516]
When MONGO_TLS is not provided as an environment variable, the check [here](https://github.com/nosqlclient/nosqlclient/blob/master/.docker/entrypoint.sh#L58) assumes it is unset as well which is not true. Same is the case for other MONGO_* vars

## Expected Behavior

Being able to start the container and connect to MongoDB

## Current Behavior

if we are using ENV vars other than MONGO_URL, container fails with the following error:
```
{"error":{"name":"MongoParseError"},"level":"error","message":"uncaughtException: Incomplete key value pair for option\nError: Incomplete key value pair for option\n    at parseQueryString (/op
t/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/uri_parser.js:370:13)\n    at parseConnectionString (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/uri_parser.js:
430:21)\n    at connect (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/mongo_client_ops.js:188:3)\n    at connectOp (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mong
odb/lib/operations/mongo_client_ops.js:292:3)\n    at executeOperation (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:420:24)\n    at MongoClient.connect (/opt/meteor/dist/bundle/programs/server/npm/node_module
s/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:168:10)\n    at Function.MongoClient.connect (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:372:22)\n    at new MongoConnection (packages/mongo
/mongo_driver.js:177:11)\n    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)\n    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)\n    at Object.defaultRemoteCollectionDriver (packages/underscore.js:
784:19)\n    at new Collection (packages/mongo/collection.js:97:40)\n    at collections.js (lib/imports/collections.js:3:24)\n    at fileEvaluate (packages/modules-runtime.js:336:7)\n    at Module.require (packages/modules-runtime.js:238:14)\n    at Module.moduleLink [as
link] (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)","stack":"Error: Incomplete key value pair for option\n    at parseQueryString (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/np
m-mongo/node_modules/mongodb-core/lib/uri_parser.js:370:13)\n    at parseConnectionString (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/uri_parser.js:430:21)\n    at connect (/opt/meteor/dist/bundle/programs/serve
r/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/mongo_client_ops.js:188:3)\n    at connectOp (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/mongo_client_ops.js:292:3)\n    at executeOp
eration (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:420:24)\n    at MongoClient.connect (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:168
:10)\n    at Function.MongoClient.connect (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:372:22)\n    at new MongoConnection (packages/mongo/mongo_driver.js:177:11)\n    at new MongoInternals.RemoteColle
ctionDriver (packages/mongo/remote_collection_driver.js:4:16)\n    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)\n    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)\n    at new Collection (packages/mongo/collection.js:97
:40)\n    at collections.js (lib/imports/collections.js:3:24)\n    at fileEvaluate (packages/modules-runtime.js:336:7)\n    at Module.require (packages/modules-runtime.js:238:14)\n    at Module.moduleLink [as link] (/opt/meteor/dist/bundle/programs/server/npm/node_modules
/meteor/modules/node_modules/reify/lib/runtime/index.js:38:38)","exception":true,"date":"Sat Aug 03 2019 18:12:14 GMT+0000 (UTC)","process":{"pid":1,"uid":1000,"gid":999,"cwd":"/opt/meteor/dist/bundle/programs/server","execPath":"/opt/nodejs/bin/node","version":"v8.4.0","
argv":["/opt/nodejs/bin/node","/opt/meteor/dist/bundle/main.js","program.json"],"memoryUsage":{"rss":119209984,"heapTotal":86953984,"heapUsed":53557816,"external":20319036}},"os":{"loadavg":[1,0.70458984375,0.47802734375],"uptime":2735},"trace":[{"column":13,"file":"/opt/
meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/uri_parser.js","function":"parseQueryString","line":370,"method":null,"native":false},{"column":21,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/np
m-mongo/node_modules/mongodb-core/lib/uri_parser.js","function":"parseConnectionString","line":430,"method":null,"native":false},{"column":3,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/mongo_client_
ops.js","function":"connect","line":188,"method":null,"native":false},{"column":3,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/mongo_client_ops.js","function":"connectOp","line":292,"method":null,"na
tive":false},{"column":24,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js","function":"executeOperation","line":420,"method":null,"native":false},{"column":10,"file":"/opt/meteor/dist/bundle/programs/serv
er/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js","function":"MongoClient.connect","line":168,"method":"connect","native":false},{"column":22,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongod
b/lib/mongo_client.js","function":"Function.MongoClient.connect","line":372,"method":"connect","native":false},{"column":11,"file":"packages/mongo/mongo_driver.js","function":"new MongoConnection","line":177,"method":null,"native":false},{"column":16,"file":"packages/mong
o/remote_collection_driver.js","function":"new MongoInternals.RemoteCollectionDriver","line":4,"method":"RemoteCollectionDriver","native":false},{"column":10,"file":"packages/mongo/remote_collection_driver.js","function":null,"line":38,"method":null,"native":false},{"colu
mn":19,"file":"packages/underscore.js","function":"Object.defaultRemoteCollectionDriver","line":784,"method":"defaultRemoteCollectionDriver","native":false},{"column":40,"file":"packages/mongo/collection.js","function":"new Collection","line":97,"method":null,"native":fal
se},{"column":24,"file":"lib/imports/collections.js","function":"collections.js","line":3,"method":"js","native":false},{"column":7,"file":"packages/modules-runtime.js","function":"fileEvaluate","line":336,"method":null,"native":false},{"column":14,"file":"packages/module
s-runtime.js","function":"Module.require","line":238,"method":"require","native":false},{"column":38,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js","function":"Module.moduleLink [as link]","line":38
,"method":"moduleLink [as link]","native":false}]}
```

## Possible Solution

Remove the checks for var set/unset

## Steps to Reproduce (for bugs)

Set MONGO_* vars (other than MONGO_URL) for an unencrypted MongoDB (MONGO_TLS not set as env var) and start the container which will fail with the above error

## Your Environment

* Nosqlclient version used: latest
* Environment name (e.g. chrome 39, portable, docker): docker version on local machine used for testing `19.03.1, build 74b1e89`
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): 18.04

**Comment by rsercano** [comment]
Thanks @junaid-ali
