### ISSUE TITLE
Failed to create lock file on read-only directory

### ISSUE THREAD

**Issue by ksafranski** [nosqlclient/nosqlclient#519]
## Expected Behavior
Docker instantiation should start without errors.

## Current Behavior

I've tried running this both with and without `--priveleged`:

```
docker run -p 3002:3000 --privileged -v /home/fluidbyte/mongoclient:/data/db mongoclient/mongoclient
```

The below output:
```
=> Starting app on port 3000...
2019-08-26T23:47:38.344+0000 I CONTROL  [initandlisten] MongoDB starting : pid=13 port=27017 dbpath=/data/db 64-bit host=0f0e276fb272
2019-08-26T23:47:38.344+0000 I CONTROL  [initandlisten] db version v3.4.2
2019-08-26T23:47:38.344+0000 I CONTROL  [initandlisten] git version: 3f76e40c105fc223b3e5aac3e20dcd026b83b38b
2019-08-26T23:47:38.344+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
2019-08-26T23:47:38.344+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2019-08-26T23:47:38.344+0000 I CONTROL  [initandlisten] modules: none
2019-08-26T23:47:38.344+0000 I CONTROL  [initandlisten] build environment:
2019-08-26T23:47:38.344+0000 I CONTROL  [initandlisten]     distmod: debian81
2019-08-26T23:47:38.344+0000 I CONTROL  [initandlisten]     distarch: x86_64
2019-08-26T23:47:38.344+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2019-08-26T23:47:38.344+0000 I CONTROL  [initandlisten] options: { storage: { engine: "wiredTiger" } }
2019-08-26T23:47:38.344+0000 I STORAGE  [initandlisten] exception in initAndListen: 20 Attempted to create a lock file on a read-only directory: /data/db, terminating
2019-08-26T23:47:38.344+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
2019-08-26T23:47:38.344+0000 I NETWORK  [initandlisten] shutdown: going to flush diaglog...
2019-08-26T23:47:38.344+0000 I CONTROL  [initandlisten] now exiting
2019-08-26T23:47:38.344+0000 I CONTROL  [initandlisten] shutting down with code:100

/opt/meteor/dist/bundle/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^
MongoError: failed to connect to server [127.0.0.1:27017] on first connect
    at Object.Future.wait (/opt/meteor/dist/bundle/programs/server/node_modules/fibers/future.js:449:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:211:27)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Mongo.Collection (packages/mongo/collection.js:99:40)
    at meteorInstall.lib.imports.collections.settings.js (lib/imports/collections/settings.js:6:25)
    at fileEvaluate (packages/modules-runtime.js:197:9)
    at Module.require (packages/modules-runtime.js:120:16)
    at Module.Mp.importSync (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime.js:82:24)
    - - - - -
    at [object Object].<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at emitOne (events.js:77:13)
    at [object Object].emit (events.js:169:7)
    at [object Object].<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at [object Object].g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at [object Object].emit (events.js:172:7)
    at Socket.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
```

**Comment by rsercano** [comment]
If you don't have much connections I suggest an easy fix for this, you can just remove the image and re-create. But that would lose settings & connections. 

That's probably a failing gracefully shutdown issue. What you can do is, start a mongod instance with `dbpath` showing the volume you gave to the mongoclient, and then just use `mongoexport` to export settings & connections, then you can completely remove docker image and the volume and re-pull. 

Afterwards you can just `mongoimport` back your settings & connections.

**Comment by rsercano** [comment]
Please feel free to re-open, closing for now.
