### ISSUE TITLE
Docker - Connections randomly lost when connecting to mongo with replicaSet

### ISSUE THREAD

**Issue by z-tc** [nosqlclient/nosqlclient#523]
While using mongoclient in Docker environment, very often connections are lost. We are connectiong to mongo with replicaSet.

## Expected Behavior
Shouldn't lose connections

## Current Behavior
Connections lost with exception from docker container:

{"error":{},"level":"error","message":"uncaughtException: other.isNegative is not a function\nTypeError: other.isNegative

## Your Environment
* Nosqlclient version used: mongoclient/mongoclient:latest

**Comment by rsercano** [comment]
Thanks for submitting it, I'll check it when I get spare time

**Comment by slesinger** [comment]
Hi, may I ask how often it happens? It happens to me every other query which renders it almost unsuable.

**Comment by rsercano** [comment]
I'm unable to check that right now, it takes so much time to setup a proper replica set on my own, any test result would be appreciated :)

**Comment by kulheim** [comment]
Hi, maybe the same problem whit docker latest image.
- Change document and save (success)
- After 3-7 sec the whole container restarts:
`{"error":{},"level":"error","message":"uncaughtException: other.isNegative is not a function\nTypeError: other.isNegative is not a function\n    at Timestamp.compare (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/node_modules/bson/lib/bson/timestamp.js:307:24)\n    at Timestamp.greaterThan (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/node_modules/bson/lib/bson/timestamp.js:280:15)\n    at resolveClusterTime (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/lib/topologies/shared.js:369:34)\n    at Server.set [as clusterTime] (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/lib/topologies/server.js:221:5)\n    at Connection.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/lib/connection/pool.js:429:37)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at processMessage (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/lib/connection/connection.js:364:10)\n    at Socket.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/lib/connection/connection.js:533:15)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at addChunk (_stream_readable.js:266:12)\n    at readableAddChunk (_stream_readable.js:253:11)\n    at Socket.Readable.push (_stream_readable.js:211:10)\n    at TCP.onread (net.js:585:20)","stack":"TypeError: other.isNegative is not a function\n    at Timestamp.compare (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/node_modules/bson/lib/bson/timestamp.js:307:24)\n    at Timestamp.greaterThan (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/node_modules/bson/lib/bson/timestamp.js:280:15)\n    at resolveClusterTime (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/lib/topologies/shared.js:369:34)\n    at Server.set [as clusterTime] (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/lib/topologies/server.js:221:5)\n    at Connection.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/lib/connection/pool.js:429:37)\n    at emitTwo (events.js:125:13)\n    at Connection.emit (events.js:213:7)\n    at processMessage (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/lib/connection/connection.js:364:10)\n    at Socket.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/lib/connection/connection.js:533:15)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at addChunk (_stream_readable.js:266:12)\n    at readableAddChunk (_stream_readable.js:253:11)\n    at Socket.Readable.push (_stream_readable.js:211:10)\n    at TCP.onread (net.js:585:20)","exception":true,"date":"Wed Nov 06 2019 10:26:18 GMT+0000 (UTC)","process":{"pid":1,"uid":1000,"gid":999,"cwd":"/opt/meteor/dist/bundle/programs/server","execPath":"/opt/nodejs/bin/node","version":"v8.4.0","argv":["/opt/nodejs/bin/node","/opt/meteor/dist/bundle/main.js","program.json"],"memoryUsage":{"rss":85229568,"heapTotal":63356928,"heapUsed":58424248,"external":64417826}},"os":{"loadavg":[0.8671875,1.63330078125,1.93994140625],"uptime":38587756},"trace":[{"column":24,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/node_modules/bson/lib/bson/timestamp.js","function":"Timestamp.compare","line":307,"method":"compare","native":false},{"column":15,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/node_modules/bson/lib/bson/timestamp.js","function":"Timestamp.greaterThan","line":280,"method":"greaterThan","native":false},{"column":34,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/lib/topologies/shared.js","function":"resolveClusterTime","line":369,"method":null,"native":false},{"column":5,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/lib/topologies/server.js","function":"Server.set [as clusterTime]","line":221,"method":"set [as clusterTime]","native":false},{"column":37,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/lib/connection/pool.js","function":null,"line":429,"method":null,"native":false},{"column":13,"file":"events.js","function":"emitTwo","line":125,"method":null,"native":false},{"column":7,"file":"events.js","function":"Connection.emit","line":213,"method":"emit","native":false},{"column":10,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/lib/connection/connection.js","function":"processMessage","line":364,"method":null,"native":false},{"column":15,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb-core/lib/connection/connection.js","function":null,"line":533,"method":null,"native":false},{"column":13,"file":"events.js","function":"emitOne","line":115,"method":null,"native":false},{"column":7,"file":"events.js","function":"Socket.emit","line":210,"method":"emit","native":false},{"column":12,"file":"_stream_readable.js","function":"addChunk","line":266,"method":null,"native":false},{"column":11,"file":"_stream_readable.js","function":"readableAddChunk","line":253,"method":null,"native":false},{"column":10,"file":"_stream_readable.js","function":"Socket.Readable.push","line":211,"method":"push","native":false},{"column":20,"file":"net.js","function":"TCP.onread","line":585,"method":"onread","native":false}]}`

**Comment by rsercano** [comment]
I'll check that thanks for the error logs

**Comment by nicohell** [comment]
Hi Sercan 
Same issue using SSH connection, work fine directly connected to port 27017.
Regards

**Comment by nicohell** [comment]
Sorry it's not working nor with ssh nor directly connected to mongo port. 
This issue happened since I upgrade Mongo to 4.2.

**Comment by rsercano** [comment]
Okay then I assume, replica connections are broken with 4.2 ? I'Ll check this

**Comment by nicohell** [comment]
Yes, just tell me if you need help to access replicaSet, I can build a test environment...

**Comment by nicohell** [comment]
Hi Sercan 
Did you take some time to check this issue ?

**Comment by rsercano** [comment]
Unfortunately @nicohell, hopefully I'll check this weekend.

**Comment by nicohell** [comment]
Hi @rsercano, still no fix ??

**Comment by rsercano** [comment]
Hi @nicohell having huge changes with my life within these latest months, it would be appreciated to get a PR for this, but I'll check this as soon as I find spare time...

**Comment by rsercano** [comment]
Starting to look into this.

**Comment by rsercano** [comment]
This issue seems to be coming from https://github.com/mongodb-js/mongodb-core/blob/master/lib/topologies/shared.js#L370 I've upgraded mongodb version but no luck, will raise the issue with them.

**Comment by rsercano** [comment]
I'm even unable to login their issue tracker...

**Comment by isaacpz** [comment]
@rsercano any updates on this? happy to help contribute if needed. having this same problem with mongo 4.2 & replicasets

**Comment by rsercano** [comment]
I would love to accept any contributions :) as I checked that can be related with nodejs mongodb driver, but a second eye would be great.

**Comment by MarkusKepert** [comment]
I think you are right @rsercano . I could track down this issue on 2 env's, both mongo 4.05 with replicaset...

**Comment by rsercano** [comment]
I'Ll try to find a way to fix.

**Comment by MarkusKepert** [comment]
@rsercano  I'll tried to update meteor libraries and maybe this solved the issue.
I'll give the new build tomorrow to my dev's, and i will wait for their feedback when using this instance for their mongodb operations.
If you want to test, feel free to use my beta-build: https://hub.docker.com/layers/markuskepert/nosqlclient/4.0.1-beta1

I will also create a pull request to this issue, maybe you can check this.

**Comment by rsercano** [comment]
Sure @MarkusNeviadomski, thanks for taking over this!

**Comment by hamdifourati** [comment]
Hello @MarkusNeviadomski,
I have tried your image but the error still occurs.
Can you please share the commit with  the changes I would like to take a look ? 
Thank you in advance.

**Comment by MarkusKepert** [comment]
@hamdifourati  Here is my commit:https://github.com/MarkusNeviadomski/nosqlclient/commit/a985001f34dee200d42a667c3b22b73cd244a8dc
I get today from my collegues a note, that they had no issues using my beta image with firefox, but having same issue when using Chrome as Browser. Maybe it isnt related only to Mongo Driver?

**Comment by rsercano** [comment]
That's strange, then I would like to try current version with another browser

**Comment by rsercano** [comment]
Within https://github.com/nosqlclient/nosqlclient/commit/8e9f400fe27ed39045104b5a5b1d3e2b51660521, I encountered this issue only once in a few hours, if you guys could try and let me know it would be awesome.

**Comment by pierrre** [comment]
Do you have a Docker image, so I can test it ?

**Comment by rsercano** [comment]
`latest` tag is building right now, https://hub.docker.com/repository/docker/mongoclient/mongoclient/

**Comment by pierrre** [comment]
Same crash.

And now it show a popup
```
[1009] "clusterTime" had the wrong type. Expected timestamp, found object
```
My replica set is empty, I just created it from a new container.

**Comment by rsercano** [comment]
I know the popup, but do you encounter `other.isNegative` crash still ? That's sad, I'll continue investigating

**Comment by pierrre** [comment]
Yes, it's the same error in the console
```
{"error":{},"level":"error","message":"uncaughtException: other.isNegative is not a function\nTypeError: other.isNegative is not a function\n    at Timestamp.compare (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/node_modules/bson/lib/bson/timestamp.js:307:24)
```

FYI, here is the image I'm using:
```
mongoclient/mongoclient                         latest                                     9a91ccfc190e        2 hours ago         1.18GB
```

**Comment by rsercano** [comment]
I see, thanks for helping, I'm still investigating the root cause

**Comment by rsercano** [comment]
Created a ticket on mongodb side, lets see what they say: https://jira.mongodb.org/browse/NODE-2640

**Comment by hamdifourati** [comment]
Hello,
I was able to identify the root cause of the problem. Unfortunately I was not able to go further with limiting the scope of the error. This can be handled by the driver or the nosqlclient client wrapper.
In both cases the app crashes when [receiving a non valid](url) `$clusterTime`. 

At first i thought it has to do with new mongodb cluster topology by passing `&useUnifiedTopology=true` to the connection url but instead I got a new error 
`"clusterTime" had the wrong type. Expected timestamp, found object` which confirmes  the the problem cause.  

Nevertheless, I am not sure if the nosqlclient app can catch this error and keep running to give a better user experience. 
Thank you  @rsercano for devoting your time :pray: 

BTW, you can get faster feedback by connecting to an Mongodb Atlas cluster.

**Comment by rsercano** [comment]
I'll check mate @hamdifourati thanks a lot for your nice words and helps :)

**Comment by rsercano** [comment]
Meteor issue to track "catching unCaughtException" https://github.com/meteor/meteor/issues/11083

**Comment by arihantdaga** [comment]
Hi Guys. I have also been facing the same problem and it sometimes is frustrating when the process is crashing every time i update a document. 
To fix the problem, Immaturely i just added one more function in MongoDBHelper. 
Forgive me, if this could lead to a blunder.  
```JavaScript
  removeClusterTimeResult(obj){
    if (obj.result && (typeof obj.result === 'object')) {
      if ('$clusterTime' in obj.result) {
        delete obj.result.$clusterTime;
      }
      if(obj.result.result && (typeof obj.result.result === 'object')){
        if ('$clusterTime' in obj.result.result) {
          delete obj.result.result.$clusterTime;
        }
      }
    }
  }
``` 

I am not sure what is the importance of clusterTime from the results, and how it may impact other things.  
And maybe instead of removing what we can do is set the right object type as mongo driver is expecting ? 
But what is happening is in this line https://github.com/nosqlclient/nosqlclient/blob/8e9f400fe27ed39045104b5a5b1d3e2b51660521/server/imports/core/mongodb/helper.js#L112 is when we are converting the result.$clusterTime or result.result.$clusterTime - we are sending it as `{$timestamp: "value"}`. Which is not acceptable to mongodb driver. Mongodb driver is expecting clusterTime to be of BSON timestamp.

**Comment by rsercano** [comment]
I wasnt expecting issue to be on converting side @arihantdaga how did you end up there? I couldn't see such behaviour in stacktrace?

**Comment by arihantdaga** [comment]
I was getting this in stacktrace - 
```JavaScript
{"error":{},"level":"error","message":"uncaughtException: other.isNegative is not a function\nTypeError: other.isNegative is not a function\n
at Timestamp.compare (/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/node_modules/bson/lib/bson/timestamp.js:307:24)\n
at Timestamp.greaterThan (/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/node_modules/bson/lib/bson/timestamp.js:280:15)\n
at resolveClusterTime (/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/core/topologies/shared.js:331:34)\n
at NativeTopology.serverUpdateHandler (/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/core/sdam/topology.js:520:7)\n
at Server.emit (events.js:311:20)\n
at Server.EventEmitter.emit (domain.js:482:12)\n
at Monitor.<anonymous> (/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/core/sdam/server.js:147:12)\n
at Monitor.emit (events.js:323:22)\n
at Monitor.EventEmitter.emit (domain.js:482:12)\n
at successHandler (/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/core/sdam/monitor.js:154:13)\n
at /home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/core/sdam/monitor.js:174:9\n
at MessageStream.messageHandler (/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/cmap/connection.js:270:5)\n
at MessageStream.emit (events.js:311:20)\n
at MessageStream.EventEmitter.emit (domain.js:482:12)\n
at processIncomingData (/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/cmap/message_stream.js:144:12)\n
at MessageStream._write (/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/cmap/message_stream.js:42:5)","stack":"TypeError: other.isNegative is not a function\n
at Timestamp.compare (/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/node_modules/bson/lib/bson/timestamp.js:307:24)\n
at Timestamp.greaterThan (/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/node_modules/bson/lib/bson/timestamp.js:280:15)\n
at resolveClusterTime (/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/core/topologies/shared.js:331:34)\n
at NativeTopology.serverUpdateHandler (/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/core/sdam/topology.js:520:7)\n
at Server.emit (events.js:311:20)\n
at Server.EventEmitter.emit (domain.js:482:12)\n
at Monitor.<anonymous> (/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/core/sdam/server.js:147:12)\n
at Monitor.emit (events.js:323:22)\n
at Monitor.EventEmitter.emit (domain.js:482:12)\n
at successHandler (/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/core/sdam/monitor.js:154:13)\n
at /home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/core/sdam/monitor.js:174:9\n
at MessageStream.messageHandler (/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/cmap/connection.js:270:5)\n
at MessageStream.emit (events.js:311:20)\n
at MessageStream.EventEmitter.emit (domain.js:482:12)\n
at processIncomingData (/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/cmap/message_stream.js:144:12)\n
at MessageStream._write (/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/cmap/message_stream.js:42:5)","exception":true,"date":"Sun Jun 14 2020 16:02:55 GMT+0530 (India Standard Time)","process":{"pid":29181,"uid":1000,"gid":1000,"cwd":"/home/akshay/Desktop/KIOT/nosqlclient_copy/.meteor/local/build/programs/server","execPath":"/home/akshay/.meteor/packages/meteor-tool/.1.10.2.yrk2zi.4myig++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node","version":"v12.16.1","argv":["/home/akshay/.meteor/packages/meteor-tool/.1.10.2.yrk2zi.4myig++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node","/home/akshay/Desktop/KIOT/nosqlclient_copy/.meteor/local/build/main.js","program.json"],"memoryUsage":{"rss":186019840,"heapTotal":109891584,"heapUsed":77147320,"external":66043249}},"os":{"loadavg":[2.30517578125,2.2158203125,1.78955078125],"uptime":11673},"trace":[{"column":24,"file":"/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/node_modules/bson/lib/bson/timestamp.js","function":"Timestamp.compare","line":307,"method":"compare","native":false},{"column":15,"file":"/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/node_modules/bson/lib/bson/timestamp.js","function":"Timestamp.greaterThan","line":280,"method":"greaterThan","native":false},{"column":34,"file":"/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/core/topologies/shared.js","function":"resolveClusterTime","line":331,"method":null,"native":false},{"column":7,"file":"/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/core/sdam/topology.js","function":"NativeTopology.serverUpdateHandler","line":520,"method":"serverUpdateHandler","native":false},{"column":20,"file":"events.js","function":"Server.emit","line":311,"method":"emit","native":false},{"column":12,"file":"domain.js","function":"Server.EventEmitter.emit","line":482,"method":"emit","native":false},{"column":12,"file":"/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/core/sdam/server.js","function":null,"line":147,"method":null,"native":false},{"column":22,"file":"events.js","function":"Monitor.emit","line":323,"method":"emit","native":false},{"column":12,"file":"domain.js","function":"Monitor.EventEmitter.emit","line":482,"method":"emit","native":false},{"column":13,"file":"/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/core/sdam/monitor.js","function":"successHandler","line":154,"method":null,"native":false},{"column":9,"file":"/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/core/sdam/monitor.js","function":null,"line":174,"method":null,"native":false},{"column":5,"file":"/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/cmap/connection.js","function":"MessageStream.messageHandler","line":270,"method":"messageHandler","native":false},{"column":20,"file":"events.js","function":"MessageStream.emit","line":311,"method":"emit","native":false},{"column":12,"file":"domain.js","function":"MessageStream.EventEmitter.emit","line":482,"method":"emit","native":false},{"column":12,"file":"/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/cmap/message_stream.js","function":"processIncomingData","line":144,"method":null,"native":false},{"column":5,"file":"/home/akshay/Desktop/KIOT/nosqlclient_copy/node_modules/mongodb/lib/cmap/message_stream.js","function":"MessageStream._write","line":42,"method":"_write","native":false}]}
```

Is it something wrong ? What i did..

**Comment by rsercano** [comment]
No no you actually gave me a point to check @arihantdaga I will try to use Extended JSON v2 introduced here: https://docs.mongodb.com/manual/reference/mongodb-extended-json/ Bear with me.

**Comment by rsercano** [comment]
I tested with new v2 extended json and seems way better, but this's not yet fully tested by community, please let me know if you encounter anything in the meantime I'll try to add some tests. With this way we now use bson's internal EJSON module.  https://www.npmjs.com/package/bson#ejson

Big shout out to @arihantdaga
