### ISSUE TITLE
node-fibers is missing in 4.0.0 docker image

### ISSUE THREAD

**Issue by legoheld** [nosqlclient/nosqlclient#541]
I just pulled the latest 4.0.0 tag and when I run the container I get:

```
## There is an issue with `node-fibers` ##
`/opt/meteor/dist/bundle/programs/server/node_modules/fibers/bin/linux-x64-57-glibc/fibers.node` is missing.
Try running this to fix the issue: /opt/nodejs/bin/node /opt/meteor/dist/bundle/programs/server/node_modules/fibers/build
Error: Cannot find module '/opt/meteor/dist/bundle/programs/server/node_modules/fibers/bin/linux-x64-57-glibc/fibers'
at Function.Module._resolveFilename (module.js:489:15)
at Function.Module._load (module.js:439:25)
at Module.require (module.js:517:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/opt/meteor/dist/bundle/programs/server/node_modules/fibers/fibers.js:14:39)
at Module._compile (module.js:573:30)
at Module.Mp._compile (/opt/meteor/dist/bundle/programs/server/runtime.js:50:23)
at Object.Module._extensions..js (module.js:584:10)
at Module.load (module.js:507:32)
at Module.Mp.load (/opt/meteor/dist/bundle/programs/server/runtime.js:15:31)
/opt/meteor/dist/bundle/programs/server/node_modules/fibers/fibers.js:23
throw new Error('Missing binary. See message above.');
^
Error: Missing binary. See message above.
at Object.<anonymous> (/opt/meteor/dist/bundle/programs/server/node_modules/fibers/fibers.js:23:9)
at Module._compile (module.js:573:30)
at Module.Mp._compile (/opt/meteor/dist/bundle/programs/server/runtime.js:50:23)
at Object.Module._extensions..js (module.js:584:10)
at Module.load (module.js:507:32)
at Module.Mp.load (/opt/meteor/dist/bundle/programs/server/runtime.js:15:31)
at tryModuleLoad (module.js:470:12)
at Function.Module._load (module.js:462:3)
at Module.require (module.js:517:17)
at require (internal/module.js:11:18)
```
## Expected Behavior
Container should be running.

## Current Behavior
Fails to run because binaries are missing in docker image 4.0.0

**Comment by rsercano** [comment]
Checking thanks for reporting.

**Comment by rsercano** [comment]
Should be related with node version, a fix is inc.

**Comment by legoheld** [comment]
Hei, latest tag works well here! Thank you!

**Comment by rsercano** [comment]
Just pushed 4.0.0 again :) Would be ready in an hour
