### ISSUE TITLE
Docker image - failed to connect to server [127.0.0.1:27017] on first connect

### ISSUE THREAD

**Issue by tennox** [nosqlclient/nosqlclient#544]
Possibly related to #354

## Expected Behavior
nosqlclient should launch its' internal mongo and be able to use it.

## Current Behavior
I start a docker container, and it crashes as it can't connect to its' internal mongo

## Possible Solution
Maybe it needs to wait? Set up higher retry timeout  on the mongoclient?

## Steps to Reproduce (for bugs)

1. `docker run mongoclient/mongoclient`

## Your Environment

* Nosqlclient version used: latest docker image [dbaa44709e83](https://hub.docker.com/layers/mongoclient/mongoclient/latest/images/sha256-dbaa44709e83544e82698852662d97676d748e2dc5cc04576c29a2b3965aa284?context=explore)
* Environment name: docker 19.03.9
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): elementary OS Hera (ubuntu bionic)

```
$ docker run mongoclient/mongoclient                                                                                                                                                    

[-] External MONGO_URL not found. Starting local MongoDB...

=> Starting app on port 3000...
2020-06-02T11:03:44.853+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2020-06-02T11:03:44.856+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
2020-06-02T11:03:44.856+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=6 port=27017 dbpath=/data/db 64-bit host=b7caf07ca2f7
2020-06-02T11:03:44.856+0000 I  CONTROL  [initandlisten] db version v4.2.6-33-g7fd3c03
2020-06-02T11:03:44.856+0000 I  CONTROL  [initandlisten] git version: 7fd3c03c548d0febfa1e871e16d638513c417c79
2020-06-02T11:03:44.856+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
2020-06-02T11:03:44.856+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
2020-06-02T11:03:44.856+0000 I  CONTROL  [initandlisten] modules: none
2020-06-02T11:03:44.856+0000 I  CONTROL  [initandlisten] build environment:
2020-06-02T11:03:44.856+0000 I  CONTROL  [initandlisten]     distmod: debian92
2020-06-02T11:03:44.856+0000 I  CONTROL  [initandlisten]     distarch: x86_64
2020-06-02T11:03:44.856+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
2020-06-02T11:03:44.856+0000 I  CONTROL  [initandlisten] options: { storage: { engine: "wiredTiger" } }
2020-06-02T11:03:44.943+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7437M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
2020-06-02T11:03:45.862+0000 I  STORAGE  [initandlisten] WiredTiger message [1591095825:862063][6:0x7f08f3a82b00], txn-recover: Set global recovery timestamp: (0, 0)
2020-06-02T11:03:46.162+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
2020-06-02T11:03:46.382+0000 I  STORAGE  [initandlisten] Timestamp monitor starting
2020-06-02T11:03:46.492+0000 I  CONTROL  [initandlisten] 
2020-06-02T11:03:46.492+0000 I  CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2020-06-02T11:03:46.492+0000 I  CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2020-06-02T11:03:46.492+0000 I  CONTROL  [initandlisten] 
2020-06-02T11:03:46.492+0000 I  CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2020-06-02T11:03:46.492+0000 I  CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2020-06-02T11:03:46.492+0000 I  CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2020-06-02T11:03:46.492+0000 I  CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2020-06-02T11:03:46.492+0000 I  CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2020-06-02T11:03:46.492+0000 I  CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2020-06-02T11:03:46.492+0000 I  CONTROL  [initandlisten] 
2020-06-02T11:03:46.493+0000 I  STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: 3cd70b66-4655-4696-be61-bcde901c25e4 and options: { uuid: UUID("3cd70b66-4655-4696-be61-bcde901c25e4") }
{"error":{"name":"MongoNetworkError"},"level":"error","message":"uncaughtException: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\nMongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at Pool.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/server.js:438:11)\n    at Pool.emit (events.js:311:20)\n    at Pool.EventEmitter.emit (domain.js:482:12)\n    at /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:561:14\n    at /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:994:11\n    at /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connect.js:31:7\n    at callback (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connect.js:264:5)\n    at Socket.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connect.js:294:7)\n    at Object.onceWrapper (events.js:418:26)\n    at Socket.emit (events.js:311:20)\n    at Socket.EventEmitter.emit (domain.js:482:12)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","stack":"MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at Pool.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/server.js:438:11)\n    at Pool.emit (events.js:311:20)\n    at Pool.EventEmitter.emit (domain.js:482:12)\n    at /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:561:14\n    at /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:994:11\n    at /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connect.js:31:7\n    at callback (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connect.js:264:5)\n    at Socket.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connect.js:294:7)\n    at Object.onceWrapper (events.js:418:26)\n    at Socket.emit (events.js:311:20)\n    at Socket.EventEmitter.emit (domain.js:482:12)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","exception":true,"date":"Tue Jun 02 2020 11:03:46 GMT+0000 (Coordinated Universal Time)","process":{"pid":1,"uid":1000,"gid":1000,"cwd":"/opt/meteor/dist/bundle/programs/server","execPath":"/opt/nodejs/bin/node","version":"v12.16.1","argv":["/opt/nodejs/bin/node","/opt/meteor/dist/bundle/main.js","program.json"],"memoryUsage":{"rss":117346304,"heapTotal":77504512,"heapUsed":49679976,"external":22401583}},"os":{"loadavg":[1.16650390625,1.5263671875,1.5849609375],"uptime":8368},"trace":[{"column":16,"file":"net.js","function":"TCPConnectWrap.afterConnect [as oncomplete]","line":1137,"method":"afterConnect [as oncomplete]","native":false},{"column":11,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/server.js","function":null,"line":438,"method":null,"native":false},{"column":20,"file":"events.js","function":"Pool.emit","line":311,"method":"emit","native":false},{"column":12,"file":"domain.js","function":"Pool.EventEmitter.emit","line":482,"method":"emit","native":false},{"column":14,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js","function":null,"line":561,"method":null,"native":false},{"column":11,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js","function":null,"line":994,"method":null,"native":false},{"column":7,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connect.js","function":null,"line":31,"method":null,"native":false},{"column":5,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connect.js","function":"callback","line":264,"method":null,"native":false},{"column":7,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connect.js","function":null,"line":294,"method":null,"native":false},{"column":26,"file":"events.js","function":"Object.onceWrapper","line":418,"method":"onceWrapper","native":false},{"column":20,"file":"events.js","function":"Socket.emit","line":311,"method":"emit","native":false},{"column":12,"file":"domain.js","function":"Socket.EventEmitter.emit","line":482,"method":"emit","native":false},{"column":8,"file":"internal/streams/destroy.js","function":"emitErrorNT","line":92,"method":null,"native":false},{"column":3,"file":"internal/streams/destroy.js","function":"emitErrorAndCloseNT","line":60,"method":null,"native":false},{"column":21,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":84,"method":null,"native":false}]}
```

**Comment by rsercano** [comment]
Hi @TeNNoX do you encounter this always or in a few of startups ?

**Comment by tennox** [comment]
I tried it often and it never worked.
Curiously I've now tried again, and it works... :shrug:

**Comment by rsercano** [comment]
Strange, but I'm glad it worked haha :)

**Comment by virus2016** [comment]
Not working again?

**Comment by rsercano** [comment]
Hello @virus2016 there's no issue reported related with it so far, please feel free to reopen with more details.

**Comment by virus2016** [comment]
Yeah the internal MongoDB service doesn't spin up so I just used our external one. Thanks

**Comment by rsercano** [comment]
Hi again @virus2016 I just started locally, but it's working tho.

**Comment by WashingtonSouza** [comment]
Hi, I'm having the same problem, when I run the command: **docker run --name mongoclient -p 3000:3000 --link mongodb:mongodb -d mongoclient/mongoclient** the container was created but never up, when I check the errors I see: 
`[-] External MONGO_URL not found. Starting local MongoDB...

=> Starting app on port 3000...
2021-01-03T03:42:25.024+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2021-01-03T03:42:25.025+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
2021-01-03T03:42:25.026+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=6 port=27017 dbpath=/data/db 64-bit host=d1396c227c08
2021-01-03T03:42:25.026+0000 I  CONTROL  [initandlisten] db version v4.2.10-17-g872b733
2021-01-03T03:42:25.026+0000 I  CONTROL  [initandlisten] git version: 872b733e4bfebd4572ed18992fe7649f9250ad9f
2021-01-03T03:42:25.026+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
2021-01-03T03:42:25.026+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
2021-01-03T03:42:25.026+0000 I  CONTROL  [initandlisten] modules: none
2021-01-03T03:42:25.026+0000 I  CONTROL  [initandlisten] build environment:
2021-01-03T03:42:25.026+0000 I  CONTROL  [initandlisten]     distmod: debian92
2021-01-03T03:42:25.026+0000 I  CONTROL  [initandlisten]     distarch: x86_64
2021-01-03T03:42:25.026+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
2021-01-03T03:42:25.026+0000 I  CONTROL  [initandlisten] options: { storage: { engine: "wiredTiger" } }
2021-01-03T03:42:25.027+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7400M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
2021-01-03T03:42:25.808+0000 I  STORAGE  [initandlisten] WiredTiger message [1609645345:808175][6:0x7f7c672ebb00], txn-recover: Set global recovery timestamp: (0, 0)
{"error":{"name":"MongoNetworkError"},"level":"error","message":"uncaughtException: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\nMongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {\n  name: 'MongoNetworkError',\n  [Symbol(mongoErrorContextSymbol)]: {}\n}]\n    at Pool.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/server.js:438:11)\n `

How can I solve it ?
This connection error still happening?

**Comment by rsercano** [comment]
> Hi, I'm having the same problem, when I run the command: **docker run --name mongoclient -p 3000:3000 --link mongodb:mongodb -d mongoclient/mongoclient** the container was created but never up, when I check the errors I see:
> `[-] External MONGO_URL not found. Starting local MongoDB...
> 
> => Starting app on port 3000...
> 2021-01-03T03:42:25.024+0000 I CONTROL [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
> 2021-01-03T03:42:25.025+0000 W ASIO [main] No TransportLayer configured during NetworkInterface startup
> 2021-01-03T03:42:25.026+0000 I CONTROL [initandlisten] MongoDB starting : pid=6 port=27017 dbpath=/data/db 64-bit host=d1396c227c08
> 2021-01-03T03:42:25.026+0000 I CONTROL [initandlisten] db version v4.2.10-17-g872b733
> 2021-01-03T03:42:25.026+0000 I CONTROL [initandlisten] git version: 872b733e4bfebd4572ed18992fe7649f9250ad9f
> 2021-01-03T03:42:25.026+0000 I CONTROL [initandlisten] OpenSSL version: OpenSSL 1.1.0l 10 Sep 2019
> 2021-01-03T03:42:25.026+0000 I CONTROL [initandlisten] allocator: tcmalloc
> 2021-01-03T03:42:25.026+0000 I CONTROL [initandlisten] modules: none
> 2021-01-03T03:42:25.026+0000 I CONTROL [initandlisten] build environment:
> 2021-01-03T03:42:25.026+0000 I CONTROL [initandlisten] distmod: debian92
> 2021-01-03T03:42:25.026+0000 I CONTROL [initandlisten] distarch: x86_64
> 2021-01-03T03:42:25.026+0000 I CONTROL [initandlisten] target_arch: x86_64
> 2021-01-03T03:42:25.026+0000 I CONTROL [initandlisten] options: { storage: { engine: "wiredTiger" } }
> 2021-01-03T03:42:25.027+0000 I STORAGE [initandlisten] wiredtiger_open config: create,cache_size=7400M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
> 2021-01-03T03:42:25.808+0000 I STORAGE [initandlisten] WiredTiger message [1609645345:808175][6:0x7f7c672ebb00], txn-recover: Set global recovery timestamp: (0, 0)
> {"error":{"name":"MongoNetworkError"},"level":"error","message":"uncaughtException: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {\n name: 'MongoNetworkError',\n [Symbol(mongoErrorContextSymbol)]: {}\n}]\nMongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017\n at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {\n name: 'MongoNetworkError',\n [Symbol(mongoErrorContextSymbol)]: {}\n}]\n at Pool. (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/server.js:438:11)\n `
> 
> How can I solve it ?
> This connection error still happening?

Hi @WashingtonSouza have you tried without linking first? Also I recommend you to use an external `MONGO_URL` for nosqlclient's connections & settings. That way you wouldn't rely meteor's MongoDB
