### ISSUE TITLE
uncaughtException: other.isNegative is not a function

### ISSUE THREAD

**Issue by pierrre** [nosqlclient/nosqlclient#545]
## Expected Behavior
The process should not crash.

## Current Behavior
When I'm trying to switch database, the process crashes
```
{"error":{},"level":"error","message":"uncaughtException: other.isNegative is not a function\nTypeError: other.isNegative is not a function\n    at Timestamp.compare (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/node_modules/bson/lib/bson/timestamp.js:307:24)\n    at Timestamp.greaterThan (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/node_modules/bson/lib/bson/timestamp.js:280:15)\n    at resolveClusterTime (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/lib/core/topologies/shared.js:331:34)\n    at Server.set [as clusterTime] (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/lib/core/topologies/server.js:228:5)\n    at Connection.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/lib/core/connection/pool.js:436:37)\n    at Connection.emit (events.js:311:20)\n    at Connection.EventEmitter.emit (domain.js:482:12)\n    at processMessage (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/lib/core/connection/connection.js:384:10)\n    at Socket.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/lib/core/connection/connection.js:553:15)\n    at Socket.emit (events.js:311:20)\n    at Socket.EventEmitter.emit (domain.js:482:12)\n    at addChunk (_stream_readable.js:294:12)\n    at readableAddChunk (_stream_readable.js:275:11)\n    at Socket.Readable.push (_stream_readable.js:209:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)","stack":"TypeError: other.isNegative is not a function\n    at Timestamp.compare (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/node_modules/bson/lib/bson/timestamp.js:307:24)\n    at Timestamp.greaterThan (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/node_modules/bson/lib/bson/timestamp.js:280:15)\n    at resolveClusterTime (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/lib/core/topologies/shared.js:331:34)\n    at Server.set [as clusterTime] (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/lib/core/topologies/server.js:228:5)\n    at Connection.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/lib/core/connection/pool.js:436:37)\n    at Connection.emit (events.js:311:20)\n    at Connection.EventEmitter.emit (domain.js:482:12)\n    at processMessage (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/lib/core/connection/connection.js:384:10)\n    at Socket.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/lib/core/connection/connection.js:553:15)\n    at Socket.emit (events.js:311:20)\n    at Socket.EventEmitter.emit (domain.js:482:12)\n    at addChunk (_stream_readable.js:294:12)\n    at readableAddChunk (_stream_readable.js:275:11)\n    at Socket.Readable.push (_stream_readable.js:209:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)","exception":true,"date":"Wed Jun 03 2020 07:00:49 GMT+0000 (Coordinated Universal Time)","process":{"pid":1,"uid":1000,"gid":1000,"cwd":"/opt/meteor/dist/bundle/programs/server","execPath":"/opt/nodejs/bin/node","version":"v12.16.1","argv":["/opt/nodejs/bin/node","/opt/meteor/dist/bundle/main.js","program.json"],"memoryUsage":{"rss":93425664,"heapTotal":50536448,"heapUsed":47995480,"external":58377938}},"os":{"loadavg":[1.04443359375,1.21728515625,1.09033203125],"uptime":1807},"trace":[{"column":24,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/node_modules/bson/lib/bson/timestamp.js","function":"Timestamp.compare","line":307,"method":"compare","native":false},{"column":15,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/node_modules/bson/lib/bson/timestamp.js","function":"Timestamp.greaterThan","line":280,"method":"greaterThan","native":false},{"column":34,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/lib/core/topologies/shared.js","function":"resolveClusterTime","line":331,"method":null,"native":false},{"column":5,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/lib/core/topologies/server.js","function":"Server.set [as clusterTime]","line":228,"method":"set [as clusterTime]","native":false},{"column":37,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/lib/core/connection/pool.js","function":null,"line":436,"method":null,"native":false},{"column":20,"file":"events.js","function":"Connection.emit","line":311,"method":"emit","native":false},{"column":12,"file":"domain.js","function":"Connection.EventEmitter.emit","line":482,"method":"emit","native":false},{"column":10,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/lib/core/connection/connection.js","function":"processMessage","line":384,"method":null,"native":false},{"column":15,"file":"/opt/meteor/dist/bundle/programs/server/npm/node_modules/mongodb/lib/core/connection/connection.js","function":null,"line":553,"method":null,"native":false},{"column":20,"file":"events.js","function":"Socket.emit","line":311,"method":"emit","native":false},{"column":12,"file":"domain.js","function":"Socket.EventEmitter.emit","line":482,"method":"emit","native":false},{"column":12,"file":"_stream_readable.js","function":"addChunk","line":294,"method":null,"native":false},{"column":11,"file":"_stream_readable.js","function":"readableAddChunk","line":275,"method":null,"native":false},{"column":10,"file":"_stream_readable.js","function":"Socket.Readable.push","line":209,"method":"push","native":false},{"column":23,"file":"internal/stream_base_commons.js","function":"TCP.onStreamRead","line":186,"method":"onStreamRead","native":false}]}
```

## Steps to Reproduce (for bugs)
1. Start the process
2. Try to switch to a database

## Your Environment
* Nosqlclient version used: the `4.0.0` Docker image
* Environment name (e.g. chrome 39, portable, docker): Chrome 83
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12): Arch Linux

**Comment by pierrre** [comment]
Duplicate of #523 , I didn't see it.
